title: Star HPC
lang: en
description: Star HPC â€“ at Hofstra University

remote_theme: StarHPC/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
